#!/usr/bin/env python3
"""Build element icon drawables from individually generated assets/elements/<id>.png.

Output: app/src/main/res/drawable-nodpi/element_<id>.webp and ElementIcons.kt.
Requires Pillow only.

Usage: python3 tools/build_element_icons.py [--preview out.png]
"""

import argparse
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = ROOT / "assets/elements"
RES_DIR = ROOT / "app/src/main/res/drawable-nodpi"
KOTLIN_FILE = ROOT / "app/src/main/kotlin/com/artt/alchemy/ui/components/ElementIcons.kt"

ICON_SIZE = 256
ICON_FILL = 0.94
WEBP_QUALITY = 88
VISIBLE_ALPHA = 16
EXPECTED_ELEMENT_COUNT = 180


def normalize(icon: Image.Image) -> Image.Image:
    icon = icon.convert("RGBA")
    visible = icon.getchannel("A").point(lambda value: 255 if value > VISIBLE_ALPHA else 0)
    bounds = visible.getbbox()
    if bounds is None:
        raise ValueError("element icon has no visible pixels")
    icon = icon.crop(bounds)
    scale = ICON_SIZE * ICON_FILL / max(icon.size)
    icon = icon.resize((max(1, round(icon.width * scale)), max(1, round(icon.height * scale))), Image.LANCZOS)
    canvas = Image.new("RGBA", (ICON_SIZE, ICON_SIZE), (0, 0, 0, 0))
    canvas.paste(icon, ((ICON_SIZE - icon.width) // 2, (ICON_SIZE - icon.height) // 2), icon)
    return canvas


def build_icons() -> dict[str, Image.Image]:
    sources = sorted(SOURCE_DIR.glob("*.png"))
    if len(sources) != EXPECTED_ELEMENT_COUNT:
        raise SystemExit(f"Expected {EXPECTED_ELEMENT_COUNT} element PNGs, found {len(sources)}")
    return {source.stem: normalize(Image.open(source)) for source in sources}


def write_preview(icons: dict[str, Image.Image], path: Path) -> None:
    cell, columns = 128, 12
    rows = (len(icons) + columns - 1) // columns
    sheet = Image.new("RGB", (columns * cell, rows * (cell + 14)), (24, 26, 36))
    draw = ImageDraw.Draw(sheet)
    for index, (element_id, icon) in enumerate(sorted(icons.items())):
        x, y = index % columns * cell, index // columns * (cell + 14)
        thumbnail = icon.resize((cell, cell), Image.LANCZOS)
        sheet.paste(thumbnail, (x, y), thumbnail)
        draw.text((x + 2, y + cell), element_id, fill="white")
    sheet.save(path)


def write_resources(icons: dict[str, Image.Image]) -> None:
    RES_DIR.mkdir(parents=True, exist_ok=True)
    for stale in RES_DIR.glob("element_*.webp"):
        stale.unlink()
    for element_id, icon in icons.items():
        icon.save(RES_DIR / f"element_{element_id}.webp", "WEBP", quality=WEBP_QUALITY, method=6)

    entries = "\n".join(f'    "{element_id}" to R.drawable.element_{element_id},' for element_id in sorted(icons))
    KOTLIN_FILE.write_text(
        "// Generated by tools/build_element_icons.py. Do not edit by hand.\n"
        "package com.artt.alchemy.ui.components\n\n"
        "import androidx.annotation.DrawableRes\n"
        "import com.artt.alchemy.R\n\n"
        "@DrawableRes\n"
        "fun elementIconRes(elementId: String): Int = elementIcons.getValue(elementId)\n\n"
        f"internal val elementIcons: Map<String, Int> = mapOf(\n{entries.rstrip(',')}\n)\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--preview", type=Path, help="write a labeled contact sheet instead of resources")
    args = parser.parse_args()
    icons = build_icons()
    if args.preview:
        write_preview(icons, args.preview)
    else:
        write_resources(icons)


if __name__ == "__main__":
    main()
