package com.artt.alchemy.game

object AlchemyCatalog {
    val baseElementIds: Set<String> = setOf("fire", "water", "earth", "air")

    val elements: List<ElementDefinition> = listOf(
        element("fire", "Огонь", ElementGroup.NATURE, 0xFFE4572EL),
        element("water", "Вода", ElementGroup.NATURE, 0xFF3185FBL),
        element("earth", "Земля", ElementGroup.NATURE, 0xFF8A5A44L),
        element("air", "Воздух", ElementGroup.NATURE, 0xFF6FA8D6L),
        element("steam", "Пар", ElementGroup.NATURE),
        element("mud", "Грязь", ElementGroup.NATURE),
        element("dust", "Пыль", ElementGroup.NATURE),
        element("lava", "Лава", ElementGroup.NATURE),
        element("energy", "Энергия", ElementGroup.NATURE),
        element("rain", "Дождь", ElementGroup.NATURE),
        element("stone", "Камень", ElementGroup.NATURE),
        element("wind", "Ветер", ElementGroup.NATURE),
        element("metal", "Металл", ElementGroup.NATURE),
        element("sand", "Песок", ElementGroup.NATURE),
        element("clay", "Глина", ElementGroup.NATURE),
        element("smoke", "Дым", ElementGroup.NATURE),
        element("ice", "Лёд", ElementGroup.NATURE),
        element("cloud", "Облако", ElementGroup.NATURE),
        element("plant", "Растение", ElementGroup.LIFE),
        element("ash", "Пепел", ElementGroup.NATURE),
        element("glass", "Стекло", ElementGroup.NATURE),
        element("lightning", "Молния", ElementGroup.NATURE),
        element("snow", "Снег", ElementGroup.NATURE),
        element("ocean", "Океан", ElementGroup.NATURE),
        element("mountain", "Гора", ElementGroup.NATURE),
        element("river", "Река", ElementGroup.NATURE),
        element("swamp", "Болото", ElementGroup.NATURE),
        element("tree", "Дерево", ElementGroup.LIFE),
        element("life", "Жизнь", ElementGroup.LIFE),
        element("seed", "Семя", ElementGroup.LIFE),
        element("flower", "Цветок", ElementGroup.LIFE),
        element("forest", "Лес", ElementGroup.LIFE),
        element("moss", "Мох", ElementGroup.NATURE),
        element("sky", "Небо", ElementGroup.COSMOS),
        element("sun", "Солнце", ElementGroup.COSMOS),
        element("moon", "Луна", ElementGroup.COSMOS),
        element("light", "Свет", ElementGroup.COSMOS),
        element("shadow", "Тень", ElementGroup.COSMOS),
        element("time", "Время", ElementGroup.COSMOS),
        element("crystal", "Кристалл", ElementGroup.COSMOS),
        element("salt", "Соль", ElementGroup.NATURE),
        element("wave", "Волна", ElementGroup.NATURE),
        element("fish", "Рыба", ElementGroup.LIFE),
        element("algae", "Водоросли", ElementGroup.NATURE),
        element("bird", "Птица", ElementGroup.LIFE),
        element("beast", "Зверь", ElementGroup.LIFE),
        element("human", "Человек", ElementGroup.LIFE),
        element("tool", "Инструмент", ElementGroup.MATERIAL),
        element("wood", "Древесина", ElementGroup.MATERIAL),
        element("house", "Дом", ElementGroup.CIVILIZATION),
        element("field", "Поле", ElementGroup.MATERIAL),
        element("farm", "Ферма", ElementGroup.CIVILIZATION),
        element("wheat", "Пшеница", ElementGroup.LIFE),
        element("bread", "Хлеб", ElementGroup.LIFE),
        element("cattle", "Скот", ElementGroup.LIFE),
        element("milk", "Молоко", ElementGroup.LIFE),
        element("cheese", "Сыр", ElementGroup.LIFE),
        element("meat", "Мясо", ElementGroup.LIFE),
        element("leather", "Кожа", ElementGroup.LIFE),
        element("wool", "Шерсть", ElementGroup.LIFE),
        element("cloth", "Ткань", ElementGroup.LIFE),
        element("rope", "Верёвка", ElementGroup.MATERIAL),
        element("paper", "Бумага", ElementGroup.CIVILIZATION),
        element("ink", "Чернила", ElementGroup.CIVILIZATION),
        element("book", "Книга", ElementGroup.CIVILIZATION),
        element("knowledge", "Знание", ElementGroup.CIVILIZATION),
        element("wheel", "Колесо", ElementGroup.MATERIAL),
        element("cart", "Телега", ElementGroup.MATERIAL),
        element("road", "Дорога", ElementGroup.MATERIAL),
        element("village", "Деревня", ElementGroup.CIVILIZATION),
        element("settlement", "Посёлок", ElementGroup.CIVILIZATION),
        element("city", "Город", ElementGroup.CIVILIZATION),
        element("bridge", "Мост", ElementGroup.MATERIAL),
        element("boat", "Лодка", ElementGroup.MATERIAL),
        element("sail", "Парус", ElementGroup.MATERIAL),
        element("ship", "Корабль", ElementGroup.MATERIAL),
        element("port", "Порт", ElementGroup.CIVILIZATION),
        element("net", "Сеть", ElementGroup.MATERIAL),
        element("fisherman", "Рыбак", ElementGroup.CIVILIZATION),
        element("feather", "Перо", ElementGroup.LIFE),
        element("egg", "Яйцо", ElementGroup.LIFE),
        element("nest", "Гнездо", ElementGroup.LIFE),
        element("bee", "Пчела", ElementGroup.LIFE),
        element("honey", "Мёд", ElementGroup.LIFE),
        element("fruit", "Фрукт", ElementGroup.LIFE),
        element("vegetable", "Овощ", ElementGroup.LIFE),
        element("herbs", "Травы", ElementGroup.LIFE),
        element("medicine", "Лекарство", ElementGroup.LIFE),
        element("poison", "Яд", ElementGroup.LIFE),
        element("mushroom", "Гриб", ElementGroup.LIFE),
        element("bone", "Кость", ElementGroup.LIFE),
        element("skull", "Череп", ElementGroup.LIFE),
        element("blood", "Кровь", ElementGroup.LIFE),
        element("corpse", "Труп", ElementGroup.LIFE),
        element("ghost", "Призрак", ElementGroup.LIFE),
        element("spirit", "Дух", ElementGroup.LIFE),
        element("cemetery", "Кладбище", ElementGroup.CIVILIZATION),
        element("grave", "Могила", ElementGroup.CIVILIZATION),
        element("wolf", "Волк", ElementGroup.LIFE),
        element("horse", "Лошадь", ElementGroup.LIFE),
        element("rider", "Всадник", ElementGroup.LIFE),
        element("string", "Струна", ElementGroup.MATERIAL),
        element("bow", "Лук", ElementGroup.MATERIAL),
        element("hunter", "Охотник", ElementGroup.LIFE),
        element("arrow", "Стрела", ElementGroup.MATERIAL),
        element("spear", "Копьё", ElementGroup.MATERIAL),
        element("sword", "Меч", ElementGroup.MATERIAL),
        element("shield", "Щит", ElementGroup.MATERIAL),
        element("armor", "Броня", ElementGroup.MATERIAL),
        element("warrior", "Воин", ElementGroup.LIFE),
        element("campfire", "Костёр", ElementGroup.CIVILIZATION),
        element("tent", "Палатка", ElementGroup.CIVILIZATION),
        element("camp", "Лагерь", ElementGroup.CIVILIZATION),
        element("forge", "Кузница", ElementGroup.MATERIAL),
        element("hammer", "Молот", ElementGroup.MATERIAL),
        element("plow", "Плуг", ElementGroup.MATERIAL),
        element("mine", "Шахта", ElementGroup.MATERIAL),
        element("gold", "Золото", ElementGroup.MATERIAL),
        element("silver", "Серебро", ElementGroup.MATERIAL),
        element("gem", "Самоцвет", ElementGroup.MATERIAL),
        element("crown", "Корона", ElementGroup.MATERIAL),
        element("king", "Король", ElementGroup.CIVILIZATION),
        element("queen", "Королева", ElementGroup.CIVILIZATION),
        element("castle", "Замок", ElementGroup.CIVILIZATION),
        element("tower", "Башня", ElementGroup.CIVILIZATION),
        element("temple", "Храм", ElementGroup.CIVILIZATION),
        element("statue", "Статуя", ElementGroup.CIVILIZATION),
        element("garden", "Сад", ElementGroup.CIVILIZATION),
        element("fountain", "Фонтан", ElementGroup.CIVILIZATION),
        element("park", "Парк", ElementGroup.CIVILIZATION),
        element("market", "Рынок", ElementGroup.CIVILIZATION),
        element("barrel", "Бочка", ElementGroup.MATERIAL),
        element("juice", "Сок", ElementGroup.CIVILIZATION),
        element("wine", "Вино", ElementGroup.CIVILIZATION),
        element("beer", "Пиво", ElementGroup.CIVILIZATION),
        element("tavern", "Таверна", ElementGroup.CIVILIZATION),
        element("bakery", "Пекарня", ElementGroup.CIVILIZATION),
        element("mill", "Мельница", ElementGroup.CIVILIZATION),
        element("farmer", "Фермер", ElementGroup.LIFE),
        element("baker", "Пекарь", ElementGroup.LIFE),
        element("blacksmith", "Кузнец", ElementGroup.LIFE),
        element("miner", "Шахтёр", ElementGroup.LIFE),
        element("merchant", "Торговец", ElementGroup.LIFE),
        element("scholar", "Учёный", ElementGroup.LIFE),
        element("priest", "Жрец", ElementGroup.LIFE),
        element("sailor", "Моряк", ElementGroup.LIFE),
        element("captain", "Капитан", ElementGroup.LIFE),
        element("pirate", "Пират", ElementGroup.LIFE),
        element("storm", "Буря", ElementGroup.NATURE),
        element("hurricane", "Ураган", ElementGroup.NATURE),
        element("blizzard", "Метель", ElementGroup.NATURE),
        element("volcano", "Вулкан", ElementGroup.NATURE),
        element("desert", "Пустыня", ElementGroup.NATURE),
        element("oasis", "Оазис", ElementGroup.NATURE),
        element("jungle", "Джунгли", ElementGroup.NATURE),
        element("island", "Остров", ElementGroup.NATURE),
        element("beach", "Пляж", ElementGroup.NATURE),
        element("coral", "Коралл", ElementGroup.NATURE),
        element("shark", "Акула", ElementGroup.LIFE),
        element("mermaid", "Русалка", ElementGroup.LIFE),
        element("dragon", "Дракон", ElementGroup.LIFE),
        element("phoenix", "Феникс", ElementGroup.LIFE),
        element("griffin", "Грифон", ElementGroup.LIFE),
        element("unicorn", "Единорог", ElementGroup.LIFE),
        element("golem", "Голем", ElementGroup.LIFE),
        element("magic", "Магия", ElementGroup.COSMOS),
        element("wizard", "Волшебник", ElementGroup.LIFE),
        element("alchemy", "Алхимия", ElementGroup.COSMOS),
        element("rune", "Руна", ElementGroup.MATERIAL),
        element("potion", "Зелье", ElementGroup.MATERIAL),
        element("elixir", "Эликсир", ElementGroup.MATERIAL),
        element("portal", "Портал", ElementGroup.COSMOS),
        element("spellbook", "Книга заклинаний", ElementGroup.COSMOS),
        element("enchantment", "Зачарование", ElementGroup.MATERIAL),
        element("clock", "Часы", ElementGroup.MATERIAL),
        element("hourglass", "Песочные часы", ElementGroup.MATERIAL),
        element("star", "Звезда", ElementGroup.COSMOS),
        element("observatory", "Обсерватория", ElementGroup.COSMOS),
        element("astronomer", "Астроном", ElementGroup.LIFE),
        element("philosopher_stone", "Философский камень", ElementGroup.COSMOS)
    )

    val elementsById: Map<String, ElementDefinition> =
        elements.associateBy(ElementDefinition::id).also { definitions ->
            check(definitions.size == elements.size) { "Element IDs must be unique" }
            check(elements.size == 180) { "Catalog must contain exactly 180 elements" }
            check(baseElementIds.all(definitions::containsKey)) { "Base elements must exist" }
        }

    val recipes: List<Recipe> = curatedRecipes()

    val recipeResultsByKey: Map<String, String> =
        recipes.associate { recipe -> recipeKey(recipe.firstId, recipe.secondId) to recipe.resultId }.also { results ->
            check(recipes.size == 176) { "Catalog must contain exactly 176 recipes" }
            check(results.size == recipes.size) { "Recipe ingredient pairs must be unique" }
            check(
                recipes.all { recipe ->
                    recipe.firstId in elementsById &&
                        recipe.secondId in elementsById &&
                        recipe.resultId in elementsById
                }
            ) { "Recipes may only reference catalog elements" }
        }

    private fun element(id: String, name: String, group: ElementGroup, color: Long = group.color): ElementDefinition = ElementDefinition(id = id, name = name, group = group, color = color)
}
