package com.artt.alchemy.game

object AlchemyCatalog {
    val baseElementIds: Set<String> = setOf("fire", "water", "earth", "air")

    val elements: List<ElementDefinition> = listOf(
        element("fire", ElementGroup.NATURE, 0xFFE4572EL),
        element("water", ElementGroup.NATURE, 0xFF3185FBL),
        element("earth", ElementGroup.NATURE, 0xFF8A5A44L),
        element("air", ElementGroup.NATURE, 0xFF6FA8D6L),
        element("steam", ElementGroup.NATURE),
        element("mud", ElementGroup.NATURE),
        element("dust", ElementGroup.NATURE),
        element("lava", ElementGroup.NATURE),
        element("energy", ElementGroup.NATURE),
        element("rain", ElementGroup.NATURE),
        element("stone", ElementGroup.NATURE),
        element("wind", ElementGroup.NATURE),
        element("metal", ElementGroup.NATURE),
        element("sand", ElementGroup.NATURE),
        element("clay", ElementGroup.NATURE),
        element("smoke", ElementGroup.NATURE),
        element("ice", ElementGroup.NATURE),
        element("cloud", ElementGroup.NATURE),
        element("plant", ElementGroup.LIFE),
        element("ash", ElementGroup.NATURE),
        element("glass", ElementGroup.NATURE),
        element("lightning", ElementGroup.NATURE),
        element("snow", ElementGroup.NATURE),
        element("ocean", ElementGroup.NATURE),
        element("mountain", ElementGroup.NATURE),
        element("river", ElementGroup.NATURE),
        element("swamp", ElementGroup.NATURE),
        element("tree", ElementGroup.LIFE),
        element("life", ElementGroup.LIFE),
        element("seed", ElementGroup.LIFE),
        element("flower", ElementGroup.LIFE),
        element("forest", ElementGroup.LIFE),
        element("moss", ElementGroup.NATURE),
        element("sky", ElementGroup.COSMOS),
        element("sun", ElementGroup.COSMOS),
        element("moon", ElementGroup.COSMOS),
        element("light", ElementGroup.COSMOS),
        element("shadow", ElementGroup.COSMOS),
        element("time", ElementGroup.COSMOS),
        element("crystal", ElementGroup.COSMOS),
        element("salt", ElementGroup.NATURE),
        element("wave", ElementGroup.NATURE),
        element("fish", ElementGroup.LIFE),
        element("algae", ElementGroup.NATURE),
        element("bird", ElementGroup.LIFE),
        element("beast", ElementGroup.LIFE),
        element("human", ElementGroup.LIFE),
        element("tool", ElementGroup.MATERIAL),
        element("wood", ElementGroup.MATERIAL),
        element("house", ElementGroup.CIVILIZATION),
        element("field", ElementGroup.MATERIAL),
        element("farm", ElementGroup.CIVILIZATION),
        element("wheat", ElementGroup.LIFE),
        element("bread", ElementGroup.LIFE),
        element("cattle", ElementGroup.LIFE),
        element("milk", ElementGroup.LIFE),
        element("cheese", ElementGroup.LIFE),
        element("meat", ElementGroup.LIFE),
        element("leather", ElementGroup.LIFE),
        element("wool", ElementGroup.LIFE),
        element("cloth", ElementGroup.LIFE),
        element("rope", ElementGroup.MATERIAL),
        element("paper", ElementGroup.CIVILIZATION),
        element("ink", ElementGroup.CIVILIZATION),
        element("book", ElementGroup.CIVILIZATION),
        element("knowledge", ElementGroup.CIVILIZATION),
        element("wheel", ElementGroup.MATERIAL),
        element("cart", ElementGroup.MATERIAL),
        element("road", ElementGroup.MATERIAL),
        element("village", ElementGroup.CIVILIZATION),
        element("settlement", ElementGroup.CIVILIZATION),
        element("city", ElementGroup.CIVILIZATION),
        element("bridge", ElementGroup.MATERIAL),
        element("boat", ElementGroup.MATERIAL),
        element("sail", ElementGroup.MATERIAL),
        element("ship", ElementGroup.MATERIAL),
        element("port", ElementGroup.CIVILIZATION),
        element("net", ElementGroup.MATERIAL),
        element("fisherman", ElementGroup.CIVILIZATION),
        element("feather", ElementGroup.LIFE),
        element("egg", ElementGroup.LIFE),
        element("nest", ElementGroup.LIFE),
        element("bee", ElementGroup.LIFE),
        element("honey", ElementGroup.LIFE),
        element("fruit", ElementGroup.LIFE),
        element("vegetable", ElementGroup.LIFE),
        element("herbs", ElementGroup.LIFE),
        element("medicine", ElementGroup.LIFE),
        element("poison", ElementGroup.LIFE),
        element("mushroom", ElementGroup.LIFE),
        element("bone", ElementGroup.LIFE),
        element("skull", ElementGroup.LIFE),
        element("blood", ElementGroup.LIFE),
        element("corpse", ElementGroup.LIFE),
        element("ghost", ElementGroup.LIFE),
        element("spirit", ElementGroup.LIFE),
        element("cemetery", ElementGroup.CIVILIZATION),
        element("grave", ElementGroup.CIVILIZATION),
        element("wolf", ElementGroup.LIFE),
        element("horse", ElementGroup.LIFE),
        element("rider", ElementGroup.LIFE),
        element("string", ElementGroup.MATERIAL),
        element("bow", ElementGroup.MATERIAL),
        element("hunter", ElementGroup.LIFE),
        element("arrow", ElementGroup.MATERIAL),
        element("spear", ElementGroup.MATERIAL),
        element("sword", ElementGroup.MATERIAL),
        element("shield", ElementGroup.MATERIAL),
        element("armor", ElementGroup.MATERIAL),
        element("warrior", ElementGroup.LIFE),
        element("campfire", ElementGroup.CIVILIZATION),
        element("tent", ElementGroup.CIVILIZATION),
        element("camp", ElementGroup.CIVILIZATION),
        element("forge", ElementGroup.MATERIAL),
        element("hammer", ElementGroup.MATERIAL),
        element("plow", ElementGroup.MATERIAL),
        element("mine", ElementGroup.MATERIAL),
        element("gold", ElementGroup.MATERIAL),
        element("silver", ElementGroup.MATERIAL),
        element("gem", ElementGroup.MATERIAL),
        element("crown", ElementGroup.MATERIAL),
        element("king", ElementGroup.CIVILIZATION),
        element("queen", ElementGroup.CIVILIZATION),
        element("castle", ElementGroup.CIVILIZATION),
        element("tower", ElementGroup.CIVILIZATION),
        element("temple", ElementGroup.CIVILIZATION),
        element("statue", ElementGroup.CIVILIZATION),
        element("garden", ElementGroup.CIVILIZATION),
        element("fountain", ElementGroup.CIVILIZATION),
        element("park", ElementGroup.CIVILIZATION),
        element("market", ElementGroup.CIVILIZATION),
        element("barrel", ElementGroup.MATERIAL),
        element("juice", ElementGroup.CIVILIZATION),
        element("wine", ElementGroup.CIVILIZATION),
        element("beer", ElementGroup.CIVILIZATION),
        element("tavern", ElementGroup.CIVILIZATION),
        element("bakery", ElementGroup.CIVILIZATION),
        element("mill", ElementGroup.CIVILIZATION),
        element("farmer", ElementGroup.LIFE),
        element("baker", ElementGroup.LIFE),
        element("blacksmith", ElementGroup.LIFE),
        element("miner", ElementGroup.LIFE),
        element("merchant", ElementGroup.LIFE),
        element("scholar", ElementGroup.LIFE),
        element("priest", ElementGroup.LIFE),
        element("sailor", ElementGroup.LIFE),
        element("captain", ElementGroup.LIFE),
        element("pirate", ElementGroup.LIFE),
        element("storm", ElementGroup.NATURE),
        element("hurricane", ElementGroup.NATURE),
        element("blizzard", ElementGroup.NATURE),
        element("volcano", ElementGroup.NATURE),
        element("desert", ElementGroup.NATURE),
        element("oasis", ElementGroup.NATURE),
        element("jungle", ElementGroup.NATURE),
        element("island", ElementGroup.NATURE),
        element("beach", ElementGroup.NATURE),
        element("coral", ElementGroup.NATURE),
        element("shark", ElementGroup.LIFE),
        element("mermaid", ElementGroup.LIFE),
        element("dragon", ElementGroup.LIFE),
        element("phoenix", ElementGroup.LIFE),
        element("griffin", ElementGroup.LIFE),
        element("unicorn", ElementGroup.LIFE),
        element("golem", ElementGroup.LIFE),
        element("magic", ElementGroup.COSMOS),
        element("wizard", ElementGroup.LIFE),
        element("alchemy", ElementGroup.COSMOS),
        element("rune", ElementGroup.MATERIAL),
        element("potion", ElementGroup.MATERIAL),
        element("elixir", ElementGroup.MATERIAL),
        element("portal", ElementGroup.COSMOS),
        element("spellbook", ElementGroup.COSMOS),
        element("enchantment", ElementGroup.MATERIAL),
        element("clock", ElementGroup.MATERIAL),
        element("hourglass", ElementGroup.MATERIAL),
        element("star", ElementGroup.COSMOS),
        element("observatory", ElementGroup.COSMOS),
        element("astronomer", ElementGroup.LIFE),
        element("philosopher_stone", ElementGroup.COSMOS)
    )

    val elementsById: Map<String, ElementDefinition> =
        elements.associateBy(ElementDefinition::id).also { definitions ->
            check(definitions.size == elements.size) { "Element IDs must be unique" }
            check(elements.size == 180) { "Catalog must contain exactly 180 elements" }
            check(baseElementIds.all(definitions::containsKey)) { "Base elements must exist" }
        }

    val recipes: List<Recipe> = allRecipes()

    val recipeResultsByKey: Map<String, String> =
        recipes.associate { recipe -> recipeKey(recipe.firstId, recipe.secondId) to recipe.resultId }.also { results ->
            check(curatedRecipes().size == 176) { "Catalog must contain exactly 176 curated recipes" }
            check(results.size == recipes.size) { "Recipe ingredient pairs must be unique" }
            check(
                recipes.all { recipe ->
                    recipe.firstId in elementsById &&
                        recipe.secondId in elementsById &&
                        recipe.resultId in elementsById
                }
            ) { "Recipes may only reference catalog elements" }
        }

    val depthById: Map<String, Int> =
        recipeDepths(baseElementIds, recipes).also { depths ->
            check(depths.keys == elementsById.keys) { "Every element must be reachable from the base elements" }
        }

    val rarityById: Map<String, ElementRarity> = depthById.mapValues { (_, depth) -> rarityForDepth(depth) }.also { rarities ->
        val curated = recipeDepths(baseElementIds, curatedRecipes()).mapValues { (_, depth) -> rarityForDepth(depth) }
        check(rarities == curated) { "Alternative recipes must not change any element's rarity" }
    }

    private fun element(id: String, group: ElementGroup, color: Long = group.color): ElementDefinition = ElementDefinition(id = id, group = group, color = color)
}
